version: '3.8'

services:
  scifig-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=SciFig AI Statistical Engine
      - APP_VERSION=2.0.0
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - ALLOWED_ORIGINS=http://localhost:8000,https://your-domain.com
      # Add your actual Supabase credentials:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY} 
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - MAX_FILE_SIZE=52428800
      - UPLOAD_DIR=uploads
      - MAX_DATASET_SIZE=100000
      - CACHE_RESULTS=true
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  default:
    driver: bridge
