version: '3.8'

services:
  # FastAPI Backend
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://scifig:password@db:5432/scifig_ai
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=dev-secret-key-change-in-production
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./static:/app/static
    depends_on:
      - db
      - redis
    command: uvicorn scifig_api_server:app --host 0.0.0.0 --port 8000 --reload

  # PostgreSQL Database
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: scifig_ai
      POSTGRES_USER: scifig
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scifig -d scifig_ai"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  # Database migrations (run once)
  migrate:
    build: .
    environment:
      - DATABASE_URL=postgresql://scifig:password@db:5432/scifig_ai
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head
    volumes:
      - ./alembic:/app/alembic
      - ./app:/app/app

volumes:
  postgres_data:
  redis_data: 