# SciFig AI Conda Environment
# Updated January 2025 - includes all dependencies for latest functionality
# Note: After creating this environment, you may need to install additional packages:
# /opt/anaconda3/envs/scifig-ai/bin/pip install PyJWT python-jose[cryptography] supabase lifelines

name: scifig-ai
channels:
  - conda-forge
  - defaults
dependencies:
  # Python runtime
  - python=3.11
  
  # Web framework
  - fastapi
  - uvicorn
  
  # Database and ORM
  - sqlalchemy
  - alembic
  - psycopg2
  
  # Scientific computing stack
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - statsmodels
  - lifelines  # For survival analysis (Kaplan-Meier)
  
  # Development and testing
  - pytest
  - pytest-asyncio
  - pytest-cov
  - black
  - flake8
  
  # Additional packages
  - pydantic
  - python-multipart
  - aiofiles
  - python-dotenv
  - redis-py
  
  # Pip dependencies (for packages not available in conda)
  - pip
  - pip:
    - PyJWT
    - python-jose[cryptography]
    - supabase
    - lifelines  # Backup pip install 